<a href="https://colab.research.google.com/github/PalashPalBangalore/unp11/blob/main/tensorflow0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
con1= tf.constant(10)
con2= tf.constant(20.6)
con3= tf.constant('Palash Pal')
con4= tf.constant(False)
print([con1, con2, con3, con4])
tf.print([con1, con2, con3, con4])

[<tf.Tensor: shape=(), dtype=int32, numpy=10>, <tf.Tensor: shape=(), dtype=float32, numpy=20.6>, <tf.Tensor: shape=(), dtype=string, numpy=b'Palash Pal'>, <tf.Tensor: shape=(), dtype=bool, numpy=False>]
[10, 20.6, "Palash Pal", 0]


In [ ]:
!pip install git+https://github.com/ML-Challenge/learntools.git
from learntools.core import binder; binder.bind(globals())
from learntools.python.ex1 import *
print("setup complete!")
pi=3.14159
diameter= 3
radius= diameter/2
area= pi*(radius**2)
print(area)
q1.check()






  Cloning https://github.com/ML-Challenge/learntools.git to /tmp/pip-req-build-c45vna2x
  Running command git clone -q https://github.com/ML-Challenge/learntools.git /tmp/pip-req-build-c45vna2x


setup complete!
7.0685775


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>

In [ ]:
con1= tf.constant(10)
con2= tf.constant(20)
sum= con1+con2
prod= con1*con2
print("sum is ", sum)
print(prod)

sum is  tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor(200, shape=(), dtype=int32)


In [ ]:
sum= tf.constant([1, 2, 3, 4, 5])+tf.constant([5, 4, 3, 2, 1])
print(sum)

tf.Tensor([6 6 6 6 6], shape=(5,), dtype=int32)


In [ ]:
a= tf.placeholder(tf.int32)
b= a*2
a= 2
print(b)



AttributeError: ignored

In [ ]:
pi=3.14159
diameter= 3
radius= diameter/2
area= pi*(radius**2)
print(area)
q1.check()


7.0685775


<IPython.core.display.Javascript object>

<span style="color:#33cc33">Correct</span>